// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<DCsAppleMilk:defeatedcrow.chocolateGift>);
recipes.remove(<DCsAppleMilk:defeatedcrow.chocolateGift:1>);
recipes.remove(<CarpentersBlocks:itemCarpentersChisel>);
recipes.remove(<DCsAppleMilk:defeatedcrow.yuzuGatling>);
recipes.remove(<minecraft:beacon>);
recipes.remove(<minecraft:minecart>);
recipes.remove(<minecraft:comparator>);
recipes.remove(<minecraft:repeater>);
recipes.remove(<minecraft:iron_door>);
recipes.remove(<minecraft:wooden_door>);
recipes.remove(<minecraft:hopper>);
recipes.remove(<minecraft:bed>);
recipes.remove(<minecraft:anvil>);
recipes.remove(<minecraft:enchanting_table>);
recipes.remove(<minecraft:iron_bars>);
recipes.remove(<minecraft:torch>);
recipes.remove(<minecraft:heavy_weighted_pressure_plate>);
recipes.remove(<minecraft:light_weighted_pressure_plate>);
recipes.remove(<minecraft:activator_rail>);
recipes.remove(<minecraft:rail>);
recipes.remove(<minecraft:detector_rail>);
recipes.remove(<minecraft:golden_rail>);
recipes.remove(<minecraft:dispenser>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_apple:*>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:detector_rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:activator_rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_rail>);
mods.tconstruct.Smeltery.removeMelting(<TConstruct:strangeFood:1>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_shovel>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_pickaxe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_axe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_shovel>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_pickaxe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_axe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_hoe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_hoe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_sword>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_sword>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_boots>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_boots>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_boots>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<minecraft:light_weighted_pressure_plate>, [<ore:plateGold>, <ore:plateGold>]);
recipes.addShapeless(<minecraft:heavy_weighted_pressure_plate>, [<ore:plateIron>, <ore:plateIron>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<DCsAppleMilk:defeatedcrow.fossilCannon>, [[<IC2:reactorPlatingExplosive>, <IC2:reactorPlatingExplosive>, <IC2:itemPlutonium>], [<DCsAppleMilk:defeatedcrow.fossilScale>, <minecraft:nether_star>, <IC2:reactorPlatingExplosive>], [<DCsAppleMilk:defeatedcrow.yuzuGatling>, <DCsAppleMilk:defeatedcrow.fossilScale>, <IC2:reactorPlatingExplosive>]]);
recipes.addShaped(<DCsAppleMilk:defeatedcrow.yuzuGatling>, [[null, <IC2:itemRecipePart>, <minecraft:dispenser>], [null, <IC2:reactorCoolantSimple:1>, <IC2:itemRecipePart>], [<IC2:itemRecipePart:2>, <IC2:itemBatChargeAdv:26>, null]]);
recipes.addShaped(<minecraft:beacon>, [[<appliedenergistics2:tile.BlockQuartzLamp>, <appliedenergistics2:tile.BlockQuartzLamp>, <appliedenergistics2:tile.BlockQuartzLamp>], [<appliedenergistics2:tile.BlockQuartzLamp>, <minecraft:nether_star>, <appliedenergistics2:tile.BlockQuartzLamp>], [<TConstruct:decoration.multibrickmetal:7>, <TConstruct:decoration.multibrick:7>, <TConstruct:decoration.multibrickmetal:5>]]);
recipes.addShaped(<minecraft:minecart>, [[<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:gearBronze>, null, <ore:gearBronze>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <minecraft:redstone_torch>, null], [<ProjRed|Core:projectred.core.part:5>, <ProjRed|Core:projectred.core.part>, <ProjRed|Core:projectred.core.part:5>]]);
recipes.addShaped(<minecraft:repeater>, [[null, <minecraft:redstone_torch>, null], [<ProjRed|Core:projectred.core.part>, <ProjRed|Core:projectred.core.part:5>, <ProjRed|Core:projectred.core.part>]]);
recipes.addShaped(<minecraft:wooden_door>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>, <ore:stickWood>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<minecraft:iron_door>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ironRod>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:hopper>, [[<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:chestWood>, <ore:plateIron>], [null, <IC2:itemLathingTool>.reuse(), null]]);
recipes.addShaped(<minecraft:bed>, [[null, null, <ore:plankWood>], [<ore:blockWool>, <ore:blockWool>, <ore:blockWool>], [<minecraft:fence>, null, <minecraft:fence>]]);
recipes.addShaped(<minecraft:anvil>, [[<ore:blockIron>, <ore:blockIron>, <ore:blockIron>], [<IC2:itemIngot:4>, <ore:ingotIron>, <IC2:itemIngot:4>], [<IC2:itemIngot:4>, null, <IC2:itemIngot:4>]]);
recipes.addShaped(<minecraft:enchanting_table>, [[<ore:gemDiamond>, null, <ore:gemDiamond>], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>], [<IC2:itemPartCoalChunk>, <IC2:itemRecipePart:4>, <IC2:itemPartCoalChunk>]]);
recipes.addShaped(<minecraft:iron_bars> * 12, [[null, <ore:craftingToolForgeHammer>, null], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:torch> * 45, [[<ore:stickWood>, <ore:blockCoal>, <ore:stickWood>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:torch> * 5, [[<ore:stickWood>, <minecraft:coal:*>, <ore:stickWood>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:golden_rail>, [[<ore:ingotGold>, <minecraft:rail>, <ore:ingotGold>], [<ore:dustRedstone>, <ore:craftingToolForgeHammer>, <ore:dustRedstone>]]);
recipes.addShaped(<minecraft:rail> * 6, [[<ore:ingotIron>, null, <ore:ingotIron>], [<ore:ingotIron>, <ore:stickWood>, <ore:ingotIron>], [<ore:ingotIron>, <ore:craftingToolForgeHammer>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:dispenser>, [[<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>], [<minecraft:stonebrick>, <BambooMod:bamboobow>, <minecraft:stonebrick>], [<minecraft:stonebrick>, <Thaumcraft:ItemResource:1>, <minecraft:stonebrick>]]);

