// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//
import mods.ic2.ThermalCentrifuge;
import mods.ic2.Compressor;
// ================================================================================
//#MARKER REMOVE
recipes.remove(<IC2:itemCable:9>);
recipes.remove(<powersuits:powerArmorComponent:15>);
recipes.remove(<powersuits:powerArmorComponent:16>);
recipes.remove(<powersuits:powerArmorComponent:17>);
recipes.remove(<powersuits:powerArmorComponent:18>);
recipes.remove(<powersuits:powerArmorComponent:19>);
recipes.remove(<powersuits:powerArmorComponent:20>);
recipes.remove(<powersuits:powerArmorComponent:21>);
recipes.remove(<powersuits:powerArmorComponent:14>);
recipes.remove(<powersuits:powerArmorComponent:13>);
recipes.remove(<powersuits:powerArmorComponent:12>);
recipes.remove(<powersuits:powerArmorComponent:11>);
recipes.remove(<powersuits:powerArmorComponent:8>);
recipes.remove(<powersuits:powerArmorComponent:7>);
recipes.remove(<powersuits:powerArmorComponent:6>);
recipes.remove(<powersuits:item.powerFist>);
recipes.remove(<powersuits:powerArmorComponent:5>);
recipes.remove(<powersuits:powerArmorComponent:3>);
recipes.remove(<powersuits:powerArmorComponent:2>);
recipes.remove(<powersuits:powerArmorComponent:1>);
recipes.remove(<powersuits:powerArmorComponent>);
recipes.remove(<powersuits:item.powerArmorBoots>);
recipes.remove(<powersuits:item.powerArmorLeggings>);
recipes.remove(<powersuits:item.powerArmorChestplate>);
recipes.remove(<powersuits:item.powerArmorHelmet>);
recipes.remove(<powersuits:tile.tinkerTable>);
recipes.remove(<TConstruct:explosive.slime:2>);
recipes.remove(<TConstruct:explosive.slime>);
recipes.remove(<Forestry:factory:3>);
recipes.remove(<IC2:blockMachine2:3>);
recipes.remove(<IC2:blockMachine2:6>);
recipes.remove(<BambooMod:spaUnit>);
recipes.remove(<IC2:itemPartIridium>);
recipes.remove(<powersuits:powerArmorComponent:9>);
recipes.remove(<powersuits:powerArmorComponent:10>);
recipes.remove(<IC2:itemArmorQuantumBoots>);
recipes.remove(<powersuits:powerArmorComponent:4>);
recipes.remove(<IC2:itemArmorQuantumLegs>);
recipes.remove(<IC2:itemArmorQuantumChestplate>);
recipes.remove(<IC2:itemArmorQuantumHelmet>);
recipes.remove(<harvestcraft:heartybreakfastItem>);
recipes.remove(<harvestcraft:delightedmealItem>);
recipes.remove(<harvestcraft:epicbaconItem>);
recipes.remove(<DCsAppleMilk:defeatedcrow.cocktail2:6>);
recipes.remove(<DCsAppleMilk:defeatedcrow.cocktail2:3>);
recipes.remove(<IC2:itemPlates>);
recipes.remove(<IC2:itemPlates:1>);
recipes.remove(<IC2:itemPlates:2>);
recipes.remove(<IC2:itemPlates:3>);
recipes.remove(<IC2:itemPlates:4>);
recipes.remove(<IC2:itemPlates:5>);
recipes.remove(<IC2:itemPlates:6>);
recipes.remove(<IC2:upgradeModule>);
recipes.remove(<IC2:blockReactorChamber>);
recipes.remove(<IC2:reactorPlating>);
recipes.remove(<IC2:reactorPlatingExplosive>);
recipes.remove(<IC2:blockKineticGenerator:1>);
recipes.remove(<DCsAppleMilk:defeatedcrow.cocktail2:2>);
recipes.remove(<DCsAppleMilk:defeatedcrow.chocolateGift>);
recipes.remove(<DCsAppleMilk:defeatedcrow.chocolateGift:1>);
recipes.remove(<CarpentersBlocks:itemCarpentersChisel>);
recipes.remove(<DCsAppleMilk:defeatedcrow.yuzuGatling>);
recipes.remove(<minecraft:beacon>);
recipes.remove(<minecraft:minecart>);
recipes.remove(<minecraft:comparator>);
recipes.remove(<minecraft:repeater>);
recipes.remove(<minecraft:iron_door>);
recipes.remove(<minecraft:wooden_door>);
recipes.remove(<minecraft:hopper>);
recipes.remove(<minecraft:bed>);
recipes.remove(<minecraft:anvil>);
recipes.remove(<minecraft:enchanting_table>);
recipes.remove(<minecraft:iron_bars>);
recipes.remove(<minecraft:torch>);
recipes.remove(<minecraft:heavy_weighted_pressure_plate>);
recipes.remove(<minecraft:light_weighted_pressure_plate>);
recipes.remove(<minecraft:activator_rail>);
recipes.remove(<minecraft:rail>);
recipes.remove(<minecraft:detector_rail>);
recipes.remove(<minecraft:golden_rail>);
recipes.remove(<minecraft:dispenser>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_apple:*>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:detector_rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:activator_rail>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_rail>);
mods.tconstruct.Smeltery.removeMelting(<TConstruct:strangeFood:1>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_shovel>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_pickaxe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_axe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_shovel>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_pickaxe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_axe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_hoe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_hoe>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_sword>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_sword>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:chainmail_boots>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:iron_boots>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_helmet>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_chestplate>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_leggings>);
mods.tconstruct.Smeltery.removeMelting(<minecraft:golden_boots>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<harvestcraft:heartybreakfastItem>, [<ore:listAllmeatcooked>, <IC2:itemShardIridium>, <ore:foodFries>, <ore:foodBlockOrangejuice>]);
recipes.addShapeless(<harvestcraft:delightedmealItem>, [<ore:listAllmeatcooked>, <ore:foodFries>, <IC2:itemShardIridium>, <ore:foodBlockOrangejuice>, <ore:foodFriedchicken>]);
recipes.addShapeless(<harvestcraft:epicbaconItem>, [<ore:dyeBrown>, <ore:listAllmeatcooked>, <IC2:itemShardIridium>, <ore:gemLapis>, <ore:dyeMagenta>, <ore:dye>, <ore:dyeGreen>, <ore:dyeRed>, <ore:dyeLightBlue>]);
recipes.addShapeless(<DCsAppleMilk:defeatedcrow.cocktail2:6>, [<ore:dyeBrown>, <IC2:itemShardIridium>, <ore:bottleBrandy>, <ore:listAllsugar>]);
recipes.addShapeless(<DCsAppleMilk:defeatedcrow.cocktail2:3>, [<ore:bottleVodka>, <ore:listAllsugar>, <ore:foodBlockOrangejuice>, <IC2:itemShardIridium>]);
recipes.addShapeless(<IC2:reactorPlatingExplosive>, [<IC2:reactorPlating>, <IC2:itemPartAlloy>, <IC2:itemPartAlloy>, <ore:plateLead>]);
recipes.addShapeless(<IC2:reactorPlating>, [<ore:plateLead>, <IC2:itemPartAlloy>]);
recipes.addShapeless(<minecraft:light_weighted_pressure_plate>, [<ore:plateGold>, <ore:plateGold>]);
recipes.addShapeless(<minecraft:heavy_weighted_pressure_plate>, [<ore:plateIron>, <ore:plateIron>]);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates>, <liquid:copper.molten> * 288, null, false, 200);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates:2>, <liquid:bronze.molten> * 288, null, false, 200);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates:3>, <liquid:gold.molten> * 288, null, false, 200);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates:4>, <liquid:iron.molten> * 288, null, false, 200);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates:5>, <liquid:steel.molten> * 288, null, false, 200);
mods.tconstruct.Casting.addTableRecipe(<IC2:itemPlates:1>, <liquid:tin.molten> * 288, null, false, 200);
ThermalCentrifuge.addRecipe([<powersuits:powerArmorComponent:13>], <IC2:itemPartCarbonPlate> * 8, 5000);
Compressor.addRecipe(<powersuits:powerArmorComponent:16>, <powersuits:powerArmorComponent:13> * 16);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<powersuits:powerArmorComponent:21>, [[<IC2:itemCellEmpty:9>, <IC2:itemCellEmpty:9>, <IC2:itemCellEmpty:9>], [<minecraft:ice>, <ore:listAllwater>, <minecraft:ice>]]);
recipes.addShaped(<powersuits:powerArmorComponent:20>, [[<IC2:blockRubber>, <IC2:blockRubber>, <IC2:blockRubber>], [<IC2:blockMiningPipe>, <IC2:blockMiningPipe>, <IC2:blockMiningPipe>], [<IC2:blockRubber>, <IC2:blockRubber>, <IC2:blockRubber>]]);
recipes.addShaped(<powersuits:powerArmorComponent:19>, [[<ore:componentControlCircuit>, <ore:componentControlCircuit>, <ore:componentControlCircuit>], [<ore:componentControlCircuit>, <ore:componentControlCircuit>, <ore:componentControlCircuit>]]);
recipes.addShaped(<powersuits:powerArmorComponent:18>, [[<ore:componentControlCircuit>], [<ore:componentLVCapacitor>], [<ore:componentSolenoid>]]);
recipes.addShaped(<powersuits:powerArmorComponent:17>, [[<IC2:blockGenerator:3>, <IC2:blockGenerator:3>, <IC2:blockGenerator:3>], [<IC2:itemCable:3>, <minecraft:daylight_detector>, <IC2:itemCable:3>], [<IC2:itemCable:3>, null, <IC2:itemCable:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:14>, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <IC2:itemToolMEter>, <ore:plateIron>], [<ore:circuitAdvanced>, <ore:circuitAdvanced>, <ore:circuitAdvanced>]]);
recipes.addShaped(<powersuits:powerArmorComponent:12>, [[null, <appliedenergistics2:tile.BlockQuartzLamp>, null], [null, <IC2:itemDust2:2>, null], [<IC2:itemCable:3>, <ore:componentHVCapacitor>, <IC2:itemCable:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:11>, [[<IC2:itemPartAlloy>, <ore:componentMVCapacitor>, <IC2:itemPartAlloy>], [<IC2:itemPartAlloy>, <ore:componentLVCapacitor>, <IC2:itemPartAlloy>], [<ore:componentIonThruster>, <ore:componentLVCapacitor>, <ore:componentIonThruster>]]);
recipes.addShaped(<powersuits:powerArmorComponent:8>, [[<ore:slabCloth>, <ore:slabCloth>, <ore:slabCloth>], [<ore:slabCloth>, <ore:slabCloth>, <TConstruct:WoolSlab1>]]);
recipes.addShaped(<powersuits:powerArmorComponent:7>, [[<IC2:itemCable:11>, <IC2:itemBatChargeLamaCrystal:26>, <IC2:itemCable:11>], [<IC2:itemCable:3>, <IC2:itemCable:3>, <IC2:itemCable:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:6>, [[<IC2:itemCable:11>, <IC2:itemBatChargeCrystal:26>, <IC2:itemCable:11>], [<IC2:itemCable:3>, <IC2:itemCable:3>, <IC2:itemCable:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:5>, [[<IC2:itemCable:11>, <IC2:itemBatChargeRE:26>, <IC2:itemCable:11>], [<IC2:itemCable:3>, <IC2:itemCable:3>, <IC2:itemCable:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:4>, [[<ore:componentServo>, <ore:componentSolenoid>, <ore:componentServo>], [<ore:componentWiring>, <IC2:reactorVentGold:1>, <ore:componentWiring>], [null, <ore:componentWiring>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:3>, [[null, null, <IC2:itemPartCarbonPlate>], [null, <IC2:itemPartCarbonPlate>, <IC2:itemRecipePart:11>], [<IC2:itemPartCarbonPlate>, <IC2:itemRecipePart:11>, <ore:componentServo>]]);
recipes.addShaped(<powersuits:powerArmorComponent:2>, [[<IC2:itemRecipePart:1>, <ore:componentWiring>, <IC2:itemRecipePart:1>], [<ore:componentWiring>, <ore:componentSolenoid>, <ore:componentWiring>], [<IC2:itemRecipePart:1>, <ore:componentWiring>, <IC2:itemRecipePart:1>]]);
recipes.addShaped(<powersuits:powerArmorComponent:1>, [[<IC2:itemCable:2>, <ore:ingotSteel>, <IC2:itemCable:2>], [<IC2:itemCable:2>, <IC2:itemRecipePart:12>, <IC2:itemCable:2>], [<IC2:itemCable:2>, <ore:ingotSteel>, <IC2:itemCable:2>]]);
recipes.addShaped(<IC2:itemCable:9> * 6, [[<ore:glass>, <ore:glass>, <ore:glass>], [<IC2:itemDust2:2>, <ore:dustSilver>, <IC2:itemDust2:2>], [<ore:glass>, <ore:glass>, <ore:glass>]]);
recipes.addShaped(<powersuits:powerArmorComponent> * 8, [[<IC2:itemCable:9>, <IC2:itemCable:9>, <IC2:itemCable:9>], [<IC2:itemDust2:2>, <IC2:itemCable:5>, <IC2:itemDust2:2>], [<IC2:itemCable:9>, <IC2:itemCable:9>, <IC2:itemCable:9>]]);
recipes.addShaped(<powersuits:tile.tinkerTable>, [[<ore:blockEmerald>, <ore:blockEmerald>, <ore:blockEmerald>], [<IC2:blockMachine2:7>, <IC2:blockElectric:4>, <IC2:blockMachine2:6>], [<ore:stickWood>, null, <ore:stickWood>]]);
recipes.addShaped(<IC2:blockMachine2:3>, [[<IC2:itemRecipePart>, <IC2:itemBatCrystal:*>, <IC2:itemRecipePart>], [<ore:ingotIron>, <IC2:blockMachine:12>, <ore:ingotIron>], [<ore:ingotIron>, <IC2:itemRecipePart:1>, <ore:ingotIron>]]);
recipes.addShaped(<IC2:blockMachine2:6>, [[<IC2:blockAlloy>, <IC2:blockAlloy>, <IC2:blockAlloy>], [<IC2:itemcrystalmemory>, <IC2:blockMachine:12>, <IC2:itemcrystalmemory>], [<IC2:itemBatCrystal:*>, <ore:circuitAdvanced>, <IC2:itemBatCrystal:*>]]);
recipes.addShaped(<powersuits:powerArmorComponent:10>, [[<IC2:itemPartAlloy>, <ore:gemDiamond>, <ore:gemDiamond>], [<ore:gemDiamond>, <IC2:reactorVentDiamond:*>, <ore:gemDiamond>], [<IC2:itemPartAlloy>, <ore:componentPlatingBasic>, <IC2:itemPartAlloy>]]);
recipes.addShaped(<powersuits:powerArmorComponent:9>, [[<IC2:reactorPlating>, <IC2:reactorPlating>, <IC2:reactorPlating>], [<IC2:itemPartAlloy>, <IC2:itemPartAlloy>, <IC2:itemPartAlloy>]]);
recipes.addShaped(<IC2:upgradeModule>, [[null, <IC2:itemCable:6>, null], [<IC2:reactorCoolantSimple>, <IC2:reactorCoolantTriple>, <IC2:reactorCoolantSimple>], [<IC2:itemCable:3>, <IC2:itemToolMEter>, <IC2:itemCable:3>]]);
recipes.addShaped(<IC2:blockReactorChamber>, [[null, <IC2:reactorPlatingExplosive>, null], [<IC2:reactorPlatingExplosive>, <IC2:blockMachine>, <IC2:reactorPlatingExplosive>], [null, <IC2:reactorPlatingExplosive>, null]]);
recipes.addShaped(<IC2:blockKineticGenerator:1>, [[<IC2:itemPartAlloy>, <IC2:itemPartAlloy>, <IC2:itemRecipePart:12>], [<IC2:itemPartAlloy>, <IC2:itemRecipePart:6>, <ore:craftingToolForgeHammer>], [<IC2:itemCable:6>, <IC2:blockMachine3>, <IC2:itemPartAlloy>]]);
recipes.addShaped(<IC2:blockKineticGenerator>, [[<ore:craftingToolForgeHammer>.reuse(), <IC2:itemRecipePart:10>, <ore:circuitAdvanced>], [<IC2:itemRecipePart:10>, <IC2:blockKineticGenerator:1>, <IC2:itemRecipePart:10>], [<ore:circuitAdvanced>, <IC2:itemRecipePart:10>, <IC2:itemRecipePart:5>]]);
recipes.addShaped(<DCsAppleMilk:defeatedcrow.fossilCannon>, [[<IC2:reactorPlatingExplosive>, <IC2:reactorPlatingExplosive>, <IC2:itemPlutonium>], [<DCsAppleMilk:defeatedcrow.fossilScale>, <minecraft:nether_star>, <IC2:reactorPlatingExplosive>], [<DCsAppleMilk:defeatedcrow.yuzuGatling>, <DCsAppleMilk:defeatedcrow.fossilScale>, <IC2:reactorPlatingExplosive>]]);
recipes.addShaped(<DCsAppleMilk:defeatedcrow.yuzuGatling>, [[null, <IC2:itemRecipePart>, <minecraft:dispenser>], [null, <IC2:reactorCoolantSimple:1>, <IC2:itemRecipePart>], [<IC2:itemRecipePart:2>, <IC2:itemBatChargeAdv:26>, null]]);
recipes.addShaped(<minecraft:beacon>, [[<appliedenergistics2:tile.BlockQuartzLamp>, <appliedenergistics2:tile.BlockQuartzLamp>, <appliedenergistics2:tile.BlockQuartzLamp>], [<appliedenergistics2:tile.BlockQuartzLamp>, <minecraft:nether_star>, <appliedenergistics2:tile.BlockQuartzLamp>], [<TConstruct:decoration.multibrickmetal:7>, <TConstruct:decoration.multibrick:7>, <TConstruct:decoration.multibrickmetal:5>]]);
recipes.addShaped(<minecraft:minecart>, [[<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:gearBronze>, null, <ore:gearBronze>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <minecraft:redstone_torch>, null], [<ProjRed|Core:projectred.core.part:5>, <ProjRed|Core:projectred.core.part>, <ProjRed|Core:projectred.core.part:5>]]);
recipes.addShaped(<minecraft:repeater>, [[null, <minecraft:redstone_torch>, null], [<ProjRed|Core:projectred.core.part>, <ProjRed|Core:projectred.core.part:5>, <ProjRed|Core:projectred.core.part>]]);
recipes.addShaped(<minecraft:wooden_door>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>, <ore:stickWood>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<minecraft:iron_door>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ironRod>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:hopper>, [[<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:chestWood>, <ore:plateIron>], [null, <IC2:itemLathingTool>.reuse(), null]]);
recipes.addShaped(<minecraft:bed>, [[null, null, <ore:plankWood>], [<ore:blockWool>, <ore:blockWool>, <ore:blockWool>], [<minecraft:fence>, null, <minecraft:fence>]]);
recipes.addShaped(<minecraft:anvil>, [[<ore:blockIron>, <ore:blockIron>, <ore:blockIron>], [<IC2:itemIngot:4>, <ore:ingotIron>, <IC2:itemIngot:4>], [<IC2:itemIngot:4>, null, <IC2:itemIngot:4>]]);
recipes.addShaped(<minecraft:enchanting_table>, [[<ore:gemDiamond>, null, <ore:gemDiamond>], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>], [<IC2:itemPartCoalChunk>, <IC2:itemRecipePart:4>, <IC2:itemPartCoalChunk>]]);
recipes.addShaped(<minecraft:iron_bars> * 12, [[null, <ore:craftingToolForgeHammer>, null], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:torch> * 45, [[<ore:stickWood>, <ore:blockCoal>, <ore:stickWood>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:torch> * 5, [[<ore:stickWood>, <minecraft:coal:*>, <ore:stickWood>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:golden_rail>, [[<ore:ingotGold>, <minecraft:rail>, <ore:ingotGold>], [<ore:dustRedstone>, <ore:craftingToolForgeHammer>, <ore:dustRedstone>]]);
recipes.addShaped(<minecraft:rail> * 6, [[<ore:ingotIron>, null, <ore:ingotIron>], [<ore:ingotIron>, <ore:stickWood>, <ore:ingotIron>], [<ore:ingotIron>, <ore:craftingToolForgeHammer>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:dispenser>, [[<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>], [<minecraft:stonebrick>, <BambooMod:bamboobow>, <minecraft:stonebrick>], [<minecraft:stonebrick>, <Thaumcraft:ItemResource:1>, <minecraft:stonebrick>]]);
#=================================================
#TC AWAKE
mods.thaumcraft.Research.addResearch("AWAKE", "ELDRITCH", "cognitio 200, sensus 200, venenum 200, vitium 200, fames 200, lucrum 200", 1, 2, 8, <BiomesOPlenty:enderporter>);
game.setLocalization("zh_CN", "tc.research_name.AWAKE", "\u89c9\u9192\u4eea\u5f0f");
game.setLocalization("zh_CN", "tc.research_text.AWAKE", "[\u89c9\u9192] \u543e\u5df2\u770b\u7834\u8ff7\u96fe\u4e2d\u7684\u6df7\u6c8c");
mods.thaumcraft.Research.addPage("AWAKE", "derp.research_page.AWAKE");
game.setLocalization("zh_CN", "derp.research_page.AWAKE", "\u6df1\u9677\u626d\u66f2\u4e2d\u7684\u4f60\u5df2\u7ecf\u65e9\u5df2\u795e\u5fd7\u751a\u4e0d\u6e05\u9192,<BR>\u4f60\u8ba4\u4e3a\u90a3\u4e9b\u5e73\u5eb8\u795e\u79d8\u4f7f\u8eab\u4e0a\u6240\u7a7f\u7684\u7eb3\u7c73\u76d4\u7532\u5df2\u7ecf\u662f\u4e0d\u6d01\u4e4b\u7269<BR>\u5c3d\u7ba1\u4f60\u4e00\u76f4\u5411\u4ed6\u4eec\u89e3\u91ca\u4f60\u7684\u7ed3\u8bba,\u4f46\u662f\u4ed6\u4eec\u90fd\u5c3d\u53ef\u80fd\u7684\u9000\u907f\u4e09\u5206,\u4f60\u5632\u7b11\u4ed6\u4eec\u7684\u611a\u8822,\u5e76\u51b3\u5b9a\u8981\u81ea\u5df1\u6765\u8bc1\u660e\u7ed9\u4ed6\u4eec\u770b<BR>\u8fd9\u4e2a\u75af\u72c2\u7684\u60f3\u6cd5,\u4f60\u5c06\u5b83\u79f0\u4e4b\u4e3a<BR><BR>\u3010\u89c9\u9192\u4eea\u5f0f\u3011<BR>");
mods.thaumcraft.Research.addPrereq("AWAKE", "ROD_primal_staff", false);
mods.thaumcraft.Warp.addToResearch("AWAKE", 5);
mods.thaumcraft.Research.moveResearch("AWAKE", "ELDRITCH", 8, 2);
#TC HELMET
mods.thaumcraft.Research.addResearch("QUANTUMHELMET", "ELDRITCH", "tutamen 100, iter 200, perfodio 100, herba 200, vitium 100", 3, 2, 8, <IC2:itemArmorQuantumHelmet>);
game.setLocalization("zh_CN", "tc.research_name.QUANTUMHELMET", "\u90aa\u6076\u6df1\u9083\u7684\u773c\u795e");
game.setLocalization("zh_CN", "tc.research_text.QUANTUMHELMET", "[\u89c9\u9192] \u672a\u77e5\u9886\u57df");
mods.thaumcraft.Research.addPage("QUANTUMHELMET", "derp.research_page.QUANTUMHELMET");
game.setLocalization("zh_CN", "derp.research_page.QUANTUMHELMET", "\u5728\u4f60\u6f2b\u957f\u7684\u9b54\u6cd5\u7814\u7a76\u4e2d\uff0c\u4f60\u5df2\u7ecf\u8d8a\u53d1\u8d8a\u6df1\u5165\u7684\u4e86\u89e3\u8fd9\u4e2a\u6697\u9ed1\u7684\u77e5\u8bc6\u4e4b\u6d77\u4e2d,\u4f46\u6709\u4e00\u65e5\u4f60\u53d1\u73b0\u4e86\u4e0e\u4f17\u4e0d\u540c\u7684\u4e1c\u897f,\u8fd9\u662f\u4e00\u4e2a\u4f60\u4ee5\u524d\u6ca1\u6709\u89c1\u8fc7\u7684<BR>\u79d1\u6280\u4ea7\u7269<BR>,\u5b83\u4eec\u7684\u6784\u6210\u4e0e\u4f60\u8eab\u4e0a\u7684\u5e03\u6599\u5b8c\u5168\u4e0d\u4e00,\u4f60\u80fd\u5f88\u6e05\u695a\u7684\u611f\u89c9\u5230\u8fd9\u4e2a\u5934\u76d4\u6563\u53d1\u51fa\u6765\u7684\u90aa\u6076\u76ee\u5149,\u4eff\u4f5b\u5c31\u8981\u6df1\u5165\u4f60\u7684\u610f\u8bc6,\u4f46\u4f60\u51b3\u5b9a\u8fd8\u662f\u5192\u9669\u4e00\u8bd5");
mods.thaumcraft.Research.addPrereq("QUANTUMHELMET", "IRPLATE", false);
mods.thaumcraft.Warp.addToResearch("QUANTUMHELMET", 5);
mods.thaumcraft.Infusion.addRecipe("QUANTUMHELMET", <IC2:itemArmorNanoHelmet:*>, [<Thaumcraft:ItemHelmetVoidFortress>, <IC2:itemNightvisionGoggles:*>, <IC2:itemBatLamaCrystal:*>, <IC2:itemSolarHelmet>, <Thaumcraft:FocusPrimal>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>], "auram 48, potentia 128, permutatio 128, tutamen 80, iter 64, motus 128", <IC2:itemArmorQuantumHelmet:27>, 15);
mods.thaumcraft.Research.addInfusionPage("QUANTUMHELMET", <IC2:itemArmorQuantumHelmet:27>);
mods.thaumcraft.Research.refreshResearchRecipe("QUANTUMHELMET");
mods.thaumcraft.Research.moveResearch("QUANTUMHELMET", "ELDRITCH", 8, -2);
#TC CHESTPLATE
mods.thaumcraft.Research.addResearch("QUANTUMCHESTPLATE", "ELDRITCH", "metallum 100, potentia 200, alienis 100, tutamen 200, machina 100", 1, 2, 8, <IC2:itemArmorQuantumChestplate>);
game.setLocalization("zh_CN", "tc.research_name.QUANTUMCHESTPLATE", "\u4e07\u6bd2\u83ab\u4fb5");
game.setLocalization("zh_CN", "tc.research_text.QUANTUMCHESTPLATE", "[\u89c9\u9192] \u4f17\u5999\u4e4b\u95e8\u5df2\u5411\u6211\u5f00\u542f");
mods.thaumcraft.Research.addPage("QUANTUMCHESTPLATE", "derp.research_page.QUANTUMCHESTPLATE");
game.setLocalization("zh_CN", "derp.research_page.QUANTUMCHESTPLATE", "\u4f60\u8ba4\u4e3a\u865a\u7a7a\u88c5\u5907\u7ed9\u4f60\u5e26\u6765\u7684\u526f\u4f5c\u7528\u5b9e\u5728\u662f\u592a\u5927\u4e86\u002c\u800c\u4e14\u9632\u5fa1\u529b\u4e5f\u4e0d\u591f\u7406\u60f3\u002c\u8fd9\u65f6\u4f60\u521a\u521a\u4ece\u4f60\u7684\u79d1\u6280\u5b9e\u9a8c\u5ba4\u91cc\u8d70\u51fa\u6765\u002c\u8111\u4e2d\u7684\u4e00\u4e2a\u7a81\u7136\u95ea\u8fc7\u7684\u53ef\u6015\u60f3\u6cd5\u8ba9\u4f60\u77ac\u65f6\u89c9\u5f97\u4e0d\u5bd2\u800c\u6817\u002c\u4f60\u51b3\u5b9a\u5192\u9669\u6253\u9020\u4e00\u4ef6\u53ef\u4ee5\u9694\u7edd\u5916\u754c\u7edd\u5927\u90e8\u5206\u7684\u4f24\u5bb3\u7684\u62a4\u7532\u002c\u800c\u5b83\u53c8\u53ef\u4ee5\u50cf\u5965\u6cd5\u7f30\u7ef3\u4e00\u6837\u81ea\u7531\u7684\u98de\u884c\u002c\u5f88\u663e\u7136\u8fd9\u663e\u5f97\u5f88\u4e0d\u7b80\u5355\u002e");
mods.thaumcraft.Research.addPrereq("QUANTUMCHESTPLATE", "IRPLATE", false);
mods.thaumcraft.Warp.addToResearch("QUANTUMCHESTPLATE", 5);
mods.thaumcraft.Infusion.addRecipe("QUANTUMCHESTPLATE", <IC2:itemArmorNanoChestplate:*>, [<Thaumcraft:ItemChestplateVoidFortress>, <IC2:itemArmorJetpackElectric:*>, <Thaumcraft:ItemRingRunic:2>, <Thaumcraft:ItemRingRunic:3>, <IC2:itemBatLamaCrystal:*>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>], "auram 64, potentia 128, permutatio 128, tutamen 128, metallum 64, motus 128", <IC2:itemArmorQuantumChestplate:27>, 15);
mods.thaumcraft.Research.addInfusionPage("QUANTUMCHESTPLATE", <IC2:itemArmorQuantumChestplate:27>);
mods.thaumcraft.Research.refreshResearchRecipe("QUANTUMCHESTPLATE");
mods.thaumcraft.Research.moveResearch("QUANTUMCHESTPLATE", "ELDRITCH", 9, -2);
#TC LEGS
mods.thaumcraft.Research.addResearch("QUANTUMLEGS", "ELDRITCH", "mortuus 100, volatus 200, vacuos 100, lux 200, tutamen 100", 2, 0, 8, <IC2:itemArmorQuantumLegs>);
game.setLocalization("zh_CN", "tc.research_name.QUANTUMLEGS", "\u795e\u884c\u592a\u4fdd");
game.setLocalization("zh_CN", "tc.research_text.QUANTUMLEGS", "[\u89c9\u9192] \u5931\u53bb\u63a7\u5236");
mods.thaumcraft.Research.addPage("QUANTUMLEGS", "derp.research_page.QUANTUMLEGS");
game.setLocalization("zh_CN", "derp.research_page.QUANTUMLEGS", "\u5728\u4f60\u4e00\u6b21\u79d1\u5b66\u7814\u7a76\u4e2d\u002c\u4f60\u65e0\u610f\u4e2d\u5f04\u7ffb\u4e86\u4f60\u7684\u5769\u57da\u002c\u5b83\u5c06\u4f60\u7cbe\u5fc3\u7f16\u5236\u7684\u62a4\u817f\u6bc1\u6389\u4e86\u002c\u4f46\u7ec6\u770b\u4e00\u4e0b\u4e8b\u60c5\u4f3c\u4e4e\u5e76\u6ca1\u6709\u90a3\u4e48\u7cdf\u7cd5\u002c\u4f60\u51b3\u5b9a\u6e05\u7406\u4e00\u4e0b\u7ee7\u7eed\u7f16\u5236\u002c\u4f46\u4f60\u88c5\u5907\u4e0a\u8fd9\u4e2a\u62a4\u817f\u4e4b\u540e\u002c\u4f60\u5374\u611f\u53d7\u4e0d\u5230\u62a4\u817f\u7684\u91cd\u91cf\u002c\u4f3c\u4e4e\u80fd\u4e3a\u4f60\u63d0\u4f9b\u6e90\u6e90\u4e0d\u65ad\u7684\u901f\u5ea6\u002c\u4f46\u4f60\u91cd\u65b0\u5236\u4f5c\u8fd9\u4e2a\u62a4\u817f\u7684\u65f6\u5019\u002c\u4f60\u5374\u5f88\u96be\u56de\u60f3\u8d77\u5b83\u7684\u914d\u65b9\u002e\u002e\u002e");
mods.thaumcraft.Research.addPrereq("QUANTUMLEGS", "IRPLATE", false);
mods.thaumcraft.Warp.addToResearch("QUANTUMLEGS", 5);
mods.thaumcraft.Infusion.addRecipe("QUANTUMLEGS", <IC2:itemArmorNanoLegs:*>, [<Thaumcraft:ItemLeggingsVoidFortress>, <Thaumcraft:WandRod:100>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemBatLamaCrystal:*>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>], "auram 64, sensus 128, ordo 128, aer 128, lucrum 64, tutamen 128", <IC2:itemArmorQuantumLegs:27>, 15);
mods.thaumcraft.Research.addInfusionPage("QUANTUMLEGS", <IC2:itemArmorQuantumLegs:27>);
mods.thaumcraft.Research.refreshResearchRecipe("QUANTUMLEGS");
mods.thaumcraft.Research.moveResearch("QUANTUMLEGS", "ELDRITCH", 10, -2);
#TC BOOTS
mods.thaumcraft.Research.addResearch("QUANTUMBOOTS", "ELDRITCH", "tempestas 100, vinculum 200, auram 100, tenebrae 200, gelum 100", 1, 1, 8, <IC2:itemArmorQuantumBoots>);
game.setLocalization("zh_CN", "tc.research_name.QUANTUMBOOTS", "\u91cd\u751f\u7684\u6b65\u4f10");
game.setLocalization("zh_CN", "tc.research_text.QUANTUMBOOTS", "[\u89c9\u9192] \u6df1\u5165\u9aa8\u9ad3");
mods.thaumcraft.Research.addPage("QUANTUMBOOTS", "derp.research_page.QUANTUMBOOTS");
game.setLocalization("zh_CN", "derp.research_page.QUANTUMBOOTS", "\u865a\u7a7a\u5957\u88c5\u62e5\u6709\u5f3a\u70c8\u7684\u526f\u4f5c\u7528\u002c\u4f60\u4e00\u76f4\u81f4\u529b\u4e8e\u53bb\u9664\u8fd9\u79cd\u526f\u4f5c\u7528\u4ee5\u8ba9\u5b83\u4eec\u53d8\u5f97\u66f4\u52a0\u7a33\u5b9a\u002c\u4f46\u6b8a\u4e0d\u77e5\u81ea\u5df1\u5df2\u7ecf\u521b\u9020\u4e86\u8fd9\u4e2a\u5168\u65b0\u7684\u9020\u7269\u002c\u5b83\u770b\u8d77\u6765\u5df2\u7ecf\u4e0d\u518d\u50cf\u662f\u865a\u7a7a\u6750\u6599\u5236\u6210\u7684\u002c\u66f4\u50cf\u662f\u51c0\u5316\u540e\u7684\u002e\u5f53\u4f60\u7a7f\u4e0a\u8fd9\u4e2a\u9774\u5b50\u7684\u65f6\u5019\u002c\u4f60\u5f88\u6e05\u695a\u7684\u611f\u5230\u6709\u80a1\u523a\u75db\u611f\u4ece\u4f60\u7684\u811a\u5e95\u4e0b\u4f20\u6765\u002c\u4f3c\u4e4e\u6709\u80a1\u672a\u77e5\u7684\u529b\u91cf\u675f\u7f1a\u4f4f\u4f60\u7684\u53cc\u817f\u002c\u4f34\u968f\u7740\u7684\u8fd8\u6709\u524d\u6240\u672a\u6709\u7684\u7075\u6d3b\u6027\u002c\u4f60\u73b0\u5728\u80fd\u5f88\u5bb9\u6613\u7684\u8df3\u8dc3\u8fc7\u9ad8\u5899\uff0c\u800c\u4e14\u5f3a\u97e7\u7684\u9762\u6599\u4e3a\u4f60\u514d\u75ab\u4e86\u6389\u843d\u4f24\u5bb3\u002c\u4f60\u53d1\u73b0\u4f60\u81ea\u5df1\u4f3c\u4e4e\u5f00\u59cb\u6162\u6162\u5730\u4f9d\u8d56\u8fd9\u79cd\u529b\u91cf\u4e86\u002e\u002e\u002e");
mods.thaumcraft.Research.addPrereq("QUANTUMBOOTS", "IRPLATE", false);
mods.thaumcraft.Warp.addToResearch("QUANTUMBOOTS", 5);
mods.thaumcraft.Infusion.addRecipe("QUANTUMBOOTS", <IC2:itemArmorNanoBoots:*>, [<Thaumcraft:BootsTraveller>, <Thaumcraft:ItemCompassStone>, <Thaumcraft:blockTaint>, <Thaumcraft:ItemResource:12>, <IC2:itemBatLamaCrystal:*>, <Thaumcraft:ItemResource:11>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>], "auram 64, vitium 128, limus 128, aer 128, lucrum 64, tutamen 128", <IC2:itemArmorQuantumBoots:27>, 15);
mods.thaumcraft.Research.addInfusionPage("QUANTUMBOOTS", <IC2:itemArmorQuantumBoots:27>);
mods.thaumcraft.Research.refreshResearchRecipe("QUANTUMBOOTS");
mods.thaumcraft.Research.moveResearch("QUANTUMBOOTS", "ELDRITCH", 11, -2);
#TC IR
mods.thaumcraft.Research.addResearch("IRPLATE", "ELDRITCH", "fames 200, lucrum 200", 1, 2, 8, <IC2:itemPartIridium>);
game.setLocalization("zh_CN", "tc.research_name.IRPLATE", "\u6d01\u51c0\u4e4b\u7269");
game.setLocalization("zh_CN", "tc.research_text.IRPLATE", "[\u89c9\u9192] \u7eaf\u51c0\u80fd\u91cf\u7684\u7ed3\u5408\u4f53");
mods.thaumcraft.Research.addPage("IRPLATE", "derp.research_page.IRPLATE");
game.setLocalization("zh_CN", "derp.research_page.IRPLATE", "\u8fd9\u79cd\u6d01\u767d\u7684\u5408\u91d1\u62e5\u6709\u5149\u6ed1 \u67d4\u8f6f\u800c\u53c8\u6709\u575a\u97e7\u7684\u7279\u6027,\u4f60\u5f88\u5e86\u5e78\u4f60\u7684\u79d1\u5b66\u77e5\u8bc6\u53ef\u4ee5\u4e3a\u4f60\u5e26\u6765\u5982\u6b64\u6069\u8d50<BR>\u4f60\u80fd\u611f\u53d7\u5230\u8fd9\u4e2a\u5408\u91d1\u91cc\u8574\u542b\u7684\u4e0d\u5355\u53ea\u662f\u9ad8\u7aef\u7684\u79d1\u6280\u7ed3\u6676,\u66f4\u591a\u7684\u662f\u9b54\u529b<BR>\u5f88\u663e\u7136\u8fd9\u79cd\u5408\u91d1\u7684\u9020\u4ef7\u4e0d\u4f1a\u4fbf\u5b9c,\u800c\u4e14\u9700\u8981\u6c72\u53d6\u5236\u4f5c\u8005\u6781\u5927\u91cf\u7684\u9b54\u529b,\u8fd9\u4e0d\u662f\u4e00\u822c\u795e\u79d8\u4f7f\u80fd\u5236\u4f5c\u51fa\u6765\u7684,\u6216\u8bb8\u4e5f\u5c31\u53ea\u6709\u50cf\u4f60\u4e00\u6837\u7684\u795e\u79d8\u4f7f\u80fd\u591f\u9a7e\u9a6d\u8fd9\u79cd\u5408\u91d1");
mods.thaumcraft.Warp.addToResearch("IRPLATE", 4);
mods.thaumcraft.Research.addPrereq("IRPLATE", "CHOOSE", false);
mods.thaumcraft.Arcane.addShaped("IRPLATE", <IC2:itemPartIridium>, "terra 270, perditio 270, ordo 270, aer 270, aqua 270, ignis 270", [[<IC2:itemOreIridium>, <IC2:itemPartAlloy>, <IC2:itemOreIridium>], [<IC2:itemDensePlates:7>, <powersuits:powerArmorComponent:10>, <IC2:itemDensePlates:7>], [<IC2:itemOreIridium>, <IC2:itemPartAlloy>, <IC2:itemOreIridium>]]);
mods.thaumcraft.Research.addArcanePage("IRPLATE", <IC2:itemPartIridium>);
mods.thaumcraft.Research.refreshResearchRecipe("IRPLATE");
mods.thaumcraft.Research.moveResearch("IRPLATE", "ELDRITCH", 9, 0);
#TC MPS
mods.thaumcraft.Research.addResearch("MPS", "ELDRITCH", "fames 200, vinculum 200", 1, 2, 8, <powersuits:tile.tinkerTable>);
game.setLocalization("zh_CN", "tc.research_name.MPS", "\u6a21\u5757\u5316\u88c5\u7532");
game.setLocalization("zh_CN", "tc.research_text.MPS", "[MPS] \u4e07\u80fd\u7684\u76d4\u7532");
mods.thaumcraft.Research.addPage("MPS", "derp.research_page.MPS");
game.setLocalization("zh_CN", "derp.research_page.MPS", "\u91cf\u5b50\u76d4\u7532\u5f3a\u529b\u7684\u529b\u91cf\u8ba9\u4f60\u83b7\u5f97\u4e86\u4e0d\u540c\u5c42\u9762\u4e0a\u7684\u4fbf\u5229,\u4f46\u540c\u65f6\u4e5f\u4f1a\u6709\u90e8\u5206\u7684\u635f\u5931,\u6bd4\u5982\u8bf4\u63ed\u793a\u62a4\u76ee\u955c\u7684\u529f\u80fd,\u4f46\u8fd9\u4e9b\u96be\u9898\u5e76\u4e0d\u80fd\u96be\u5230\u4f5c\u4e3a\u79d1\u5b66\u5bb6\u548c\u795e\u79d8\u4f7f\u7684\u4f60,\u4f60\u51b3\u5b9a\u6253\u9020\u4e00\u4e2a\u53ef\u591a\u6837\u62c6\u5378\u90e8\u4ef6\u7684\u591a\u529f\u80fd\u5316\u7684\u62a4\u7532<BR>\u5b83\u5177\u6709\u6781\u5f3a\u7684\u50a8\u80fd\u529f\u80fd,\u8fd8\u96c6\u6210\u4e86\u6781\u591a\u7684\u529f\u80fd<BR>\u4f46\u5982\u6b64\u591a\u7684\u529f\u80fd\u4e5f\u5e26\u6765\u4e86\u5b83\u7684\u4e0d\u4fbf\u6027,\u90a3\u5c31\u662f\u590d\u6742\u7684\u88c5\u5907\u5e26\u6765\u7684\u91cd\u91cf,\u800c\u4e14\u9632\u62a4\u80fd\u529b\u4e5f\u4e0d\u53ca\u539f\u6765\u7684\u76d4\u7532,\u4f1a\u8ba9\u4f60\u884c\u52a8\u4e0d\u4fbf,\u6216\u8bb8\u4f60\u53ef\u4ee5\u901a\u8fc7\u76d4\u7532\u4e0a\u7684\u8f85\u52a9\u79fb\u52a8\u6a21\u5757\u6765\u89e3\u51b3\u8fd9\u4e9b\u95ee\u9898.");
mods.thaumcraft.Research.addPrereq("MPS", "CHOOSE", false);
mods.thaumcraft.Research.addCraftingPage("MPS", <powersuits:tile.tinkerTable>);
mods.thaumcraft.Research.refreshResearchRecipe("MPS");
mods.thaumcraft.Research.moveResearch("MPS", "ELDRITCH", 9, 4);
#TC MPS HELMET
mods.thaumcraft.Research.addResearch("MPSHELMET", "ELDRITCH", "fames 200, perditio 200", 1, 2, 8, <powersuits:item.powerArmorHelmet>);
game.setLocalization("zh_CN", "tc.research_name.MPSHELMET", "\u4e0a\u5e1d\u4e4b\u773c");
game.setLocalization("zh_CN", "tc.research_text.MPSHELMET", "[MPS] \u5f53\u4f60\u51dd\u671b\u6df1\u6e0a\u7684\u65f6\u5019,\u6df1\u6e0a\u4e5f\u5728\u6ce8\u89c6\u7740\u4f60");
mods.thaumcraft.Research.addPage("MPSHELMET", "derp.research_page.MPSHELMET");
game.setLocalization("zh_CN", "derp.research_page.MPSHELMET", "\u591a\u529f\u80fd\u7684\u5934\u76d4\u96c6\u6210\u4e86\u5927\u91cf\u7684\u529f\u80fd,\u6c34\u4e0b\u547c\u5438\u591c\u89c6\u7b49\u7b49\u7684\u529f\u80fd,\u5e76\u4e14\u4ed6\u4eec\u62e5\u6709\u91cf\u5b50\u5957\u88c55\u500d\u7684\u50a8\u80fd,\u4f46\u4e5f\u6709\u76f8\u5bf9\u5e94\u7684\u7f3a\u70b9,\u7e41\u591a\u7684\u88c5\u5907\u5e26\u6765\u7684\u91cd\u91cf,\u800c\u4e14\u6574\u4f53\u9632\u62a4\u80fd\u529b\u4e5f\u6ca1\u6709\u91cf\u5b50\u76d4\u7532\u7684\u5168\u9762");
mods.thaumcraft.Research.addPrereq("MPSHELMET", "MPS", false);
mods.thaumcraft.Warp.addToResearch("MPSHELMET", 3);
mods.thaumcraft.Infusion.addRecipe("MPSHELMET", <IC2:itemArmorNanoHelmet:*>, [<IC2:itemPartIridium>, <IC2:itemPartIridium>, <powersuits:powerArmorComponent:5>, <powersuits:powerArmorComponent:2>, <powersuits:powerArmorComponent:19>, <Thaumcraft:ItemHelmetVoidFortress>, <powersuits:powerArmorComponent:10>, <powersuits:powerArmorComponent:10>], "auram 64, instrumentum 64, meto 64, tutamen 64, metallum 64, corpus 64", <powersuits:item.powerArmorHelmet>, 9);
mods.thaumcraft.Research.addInfusionPage("MPSHELMET", <powersuits:item.powerArmorHelmet>);
mods.thaumcraft.Research.refreshResearchRecipe("MPSHELMET");
mods.thaumcraft.Research.moveResearch("MPSHELMET", "ELDRITCH", 8, 6);
#TC CHOOSE
mods.thaumcraft.Research.addResearch("CHOOSE", "ELDRITCH", "aer 200, ordo 200", 1, 2, 8, <customnpcs:npcIceSpell>);
game.setLocalization("zh_CN", "tc.research_name.CHOOSE", "\u9009\u62e9");
game.setLocalization("zh_CN", "tc.research_text.CHOOSE", "[\u89c9\u9192] \u662f\u8be5\u9009\u62e9\u4e86");
mods.thaumcraft.Research.addPage("CHOOSE", "derp.research_page.CHOOSE");
game.setLocalization("zh_CN", "derp.research_page.CHOOSE", "\u89c9\u9192\u540e\u7684\u4f60\u4eff\u4f5b\u770b\u5230\u4e86\u8bb8\u591a\u4e1c\u897f\uff0c\u4e0d\u53ea\u662f\u90a3\u4e9b\u9690\u85cf\u5728\u9ed1\u6697\u6df1\u5904\u7684\u6cd5\u529b,\u66f4\u591a\u7684\u662f\u5149\u660e,\u4e0d\u8fc7\u6446\u5728\u4f60\u9762\u524d\u7684\u5374\u662f\u4e24\u6761\u8def,\u4f60\u65e0\u610f\u95f4\u53d1\u73b0\u4e86\u4e24\u4e2a\u65b0\u79d1\u6280,\u5728\u591a\u529f\u80fd\u4e0e\u9ad8\u5f3a\u9632\u5fa1\u95f4\u4f60\u9700\u8981\u505a\u51fa\u9009\u62e9<BR>\u53c8\u6216\u8005\u662f<BR>\u5168\u90e8\u62e5\u6709\u5462\uff1f");
mods.thaumcraft.Research.addPrereq("CHOOSE", "AWAKE", false);
mods.thaumcraft.Research.moveResearch("CHOOSE", "ELDRITCH", 10, 2);
#TC MPS CHESTPLATE
mods.thaumcraft.Research.addResearch("MPSCHESTPLATE", "ELDRITCH", "fames 200, ordo 200", 1, 2, 8, <powersuits:item.powerArmorChestplate>);
game.setLocalization("zh_CN", "tc.research_name.MPSCHESTPLATE", "\u5c55\u7fc5");
game.setLocalization("zh_CN", "tc.research_text.MPSCHESTPLATE", "[MPS] \u9ad8\u65b0\u52a8\u529b\u88c5\u7532MKV");
mods.thaumcraft.Research.addPage("MPSCHESTPLATE", "derp.research_page.MPSCHESTPLATE");
game.setLocalization("zh_CN", "derp.research_page.MPSCHESTPLATE", "\u8be5\u76d4\u7532\u6574\u5408\u4e86\u5927\u91cf\u7684\u79d1\u6280\u5143\u7d20,\u50a8\u6c34,\u80fd\u91cf\u62a4\u76fe,\u989d\u5916\u7684\u98de\u884c\u8f85\u52a9\u7b49\u7b49,\u4e0d\u8fc7\u6700\u4e3a\u7279\u8272\u7684\u5143\u7d20\u5728\u4e8e\u5b83\u53ef\u4ee5\u91ca\u653e\u5f3a\u5927\u7684\u6392\u65a5\u529b\u573a,\u5c06\u654c\u5bf9\u751f\u7269\u9694\u7edd\u5728\u5916,\u4f46\u662f\u7531\u4e8e\u529b\u573a\u53d1\u751f\u5668\u7684\u8017\u80fd,\u8fd9\u4e2a\u7cfb\u7edf\u53ea\u80fd\u5f00\u542f\u5f88\u77ed\u65f6\u95f4,\u540c\u65f6\u5982\u679c\u4f60\u88c5\u5907\u539a\u91cd\u7684\u88c5\u7532,\u5b83\u5e26\u6765\u7684\u5de8\u5927\u91cd\u91cf\u4e5f\u662f\u4e00\u4e2a\u9ebb\u70e6\u7684\u95ee\u9898.");
mods.thaumcraft.Research.addPrereq("MPSCHESTPLATE", "MPS", false);
mods.thaumcraft.Warp.addToResearch("MPSCHESTPLATE", 3);
mods.thaumcraft.Infusion.addRecipe("MPSCHESTPLATE", <IC2:itemArmorNanoChestplate:*>, [<IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <powersuits:powerArmorComponent:16>, <powersuits:powerArmorComponent:10>, <powersuits:powerArmorComponent:11>, <powersuits:powerArmorComponent:7>, <powersuits:powerArmorComponent:19>, <Thaumcraft:ItemChestplateVoidFortress>], "auram 64, instrumentum 64, volatus 64, tutamen 64, metallum 64, iter 64", <powersuits:item.powerArmorChestplate>, 9);
mods.thaumcraft.Research.addInfusionPage("MPSCHESTPLATE", <powersuits:item.powerArmorChestplate>);
mods.thaumcraft.Research.refreshResearchRecipe("MPSCHESTPLATE");
mods.thaumcraft.Research.moveResearch("MPSCHESTPLATE", "ELDRITCH", 9, 6);
#TC MPS LEGS
mods.thaumcraft.Research.addResearch("MPSLEGGING", "ELDRITCH", "fames 200, aer 200", 1, 2, 8, <powersuits:item.powerArmorLeggings>);
game.setLocalization("zh_CN", "tc.research_name.MPSLEGGING", "\u884c\u5982\u75be\u98ce");
game.setLocalization("zh_CN", "tc.research_text.MPSLEGGING", "[MPS] \u9632\u5fa1\u4e0d\u7b49\u4e8e\u5b9e\u7528,\u7075\u6d3b\u624d\u662f\u5173\u952e\u6240\u5728");
mods.thaumcraft.Research.addPage("MPSLEGGING", "derp.research_page.MPSLEGGING");
game.setLocalization("zh_CN", "derp.research_page.MPSLEGGING", "\u62a4\u817f\u4e00\u822c\u5728\u673a\u68b0\u5916\u62a4\u7532\u7c7b\u522b\u91cc\u8d77\u5230\u8f85\u52a9\u7684\u4f5c\u7528,\u5f53\u7136\u4e5f\u4f1a\u6709\u4e00\u5b9a\u7684\u9632\u5fa1\u529b,\u8fd9\u4e2a\u62a4\u817f\u53ef\u4ee5\u4e3a\u4f60\u5e26\u6765\u6781\u5f3a\u7684\u79fb\u52a8\u8f85\u52a9,\u79fb\u52a8 \u6e38\u6cf3 \u722c\u5761\u7b49\u96c6\u6210\u5230\u4e00\u7ec4\u4f3a\u670d\u5668\u91cc,\u8ba9\u5176\u62e5\u6709\u5f3a\u5927\u7684\u529f\u80fd\u6027,\u4e0d\u8fc7\u540c\u65f6\u4e5f\u4f1a\u5e26\u6765\u4e0d\u5fc5\u8981\u7684\u91cd\u91cf.");
mods.thaumcraft.Research.addPrereq("MPSLEGGING", "MPS", false);
mods.thaumcraft.Warp.addToResearch("MPSLEGGING", 3);
mods.thaumcraft.Infusion.addRecipe("MPSLEGGING", <IC2:itemArmorNanoLegs:*>, [<Thaumcraft:ItemLeggingsVoidFortress>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <powersuits:powerArmorComponent:10>, <powersuits:powerArmorComponent:16>, <powersuits:powerArmorComponent:16>, <powersuits:powerArmorComponent:12>, <powersuits:powerArmorComponent:19>], "auram 64, motus 64, machina 64, tutamen 64, metallum 64, sano 64", <powersuits:item.powerArmorLeggings>, 9);
mods.thaumcraft.Research.addInfusionPage("MPSLEGGING", <powersuits:item.powerArmorLeggings>);
mods.thaumcraft.Research.refreshResearchRecipe("MPSLEGGING");
mods.thaumcraft.Research.moveResearch("MPSLEGGING", "ELDRITCH", 10, 6);
#TC MPS BOOTS
mods.thaumcraft.Research.addResearch("MPSBOOTS", "ELDRITCH", "fames 200, aqua 200", 1, 2, 8, <powersuits:item.powerArmorBoots>);
game.setLocalization("zh_CN", "tc.research_name.MPSBOOTS", "\u5982\u5c65\u5e73\u5730");
game.setLocalization("zh_CN", "tc.research_text.MPSBOOTS", "[MPS] \u7a7a\u5982\u6b62\u6c34");
mods.thaumcraft.Research.addPage("MPSBOOTS", "derp.research_page.MPSBOOTS");
game.setLocalization("zh_CN", "derp.research_page.MPSBOOTS", "\u4f5c\u4e3a\u7528\u7684\u6700\u591a\u7684\u978b\u5b50,\u96c6\u6210\u7684\u529f\u80fd\u8d8a\u591a,\u610f\u5473\u7740\u8fd9\u4e2a\u9774\u5b50\u7684\u79d1\u6280\u6c34\u5e73,\u6240\u4ee5\u4e00\u53cc\u597d\u7684\u9774\u5b50\u662f\u79d1\u6280\u6c34\u5e73\u7684\u89c1\u8bc1,\u7279\u6709\u7684\u53cd\u91cd\u529b\u55b7\u5c04\u6a21\u7ec4\u53ef\u4ee5\u5728\u7a7a\u4e2d\u77ed\u8ddd\u79bb\u98de\u884c,\u4e0d\u8fc7\u91cd\u91cf\u4e5f\u662f\u4e00\u4e2a\u786c\u4f24");
mods.thaumcraft.Research.addPrereq("MPSBOOTS", "MPS", false);
mods.thaumcraft.Warp.addToResearch("MPSBOOTS", 3);
mods.thaumcraft.Infusion.addRecipe("MPSBOOTS", <IC2:itemArmorNanoBoots:*>, [<Thaumcraft:ItemBootsVoid>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <powersuits:powerArmorComponent:3>, <powersuits:powerArmorComponent:19>, <powersuits:powerArmorComponent:6>, <powersuits:powerArmorComponent:11>, <powersuits:powerArmorComponent:10>], "auram 64, motus 64, sensus 64, tutamen 64, fames 64, sano 64", <powersuits:item.powerArmorBoots>, 9);
mods.thaumcraft.Research.addInfusionPage("MPSBOOTS", <powersuits:item.powerArmorBoots>);
mods.thaumcraft.Research.refreshResearchRecipe("MPSBOOTS");
mods.thaumcraft.Research.moveResearch("MPSBOOTS", "ELDRITCH", 11, 6);
#TC MPS HAND
mods.thaumcraft.Research.addResearch("MPSHAND", "ELDRITCH", "fames 200, perditio 200", 1, 2, 8, <powersuits:item.powerFist>);
game.setLocalization("zh_CN", "tc.research_name.MPSHAND", "\u65e0\u5c3d\u4e4b\u62f3");
game.setLocalization("zh_CN", "tc.research_text.MPSHAND", "[MPS] \u5929\u4e0b \u5c3d\u5728\u6211\u624b\u4e2d");
mods.thaumcraft.Research.addPage("MPSHAND", "derp.research_page.MPSHAND");
game.setLocalization("zh_CN", "derp.research_page.MPSHAND", "\u52a8\u529b\u62f3\u5957\u662f\u52a8\u529b\u5957\u88c5\u6700\u4e3a\u6838\u5fc3\u7684\u4e00\u4e2a\u90e8\u4ef6,\u800c\u4e14\u662f\u4f5c\u4e3a\u91cf\u5b50\u62a4\u7532\u6ca1\u6709\u7684\u4e00\u4e2a\u90e8\u4ef6,\u5b83\u5177\u6709\u6240\u6709\u5de5\u5177\u7684\u529f\u80fd,\u8fd8\u63d0\u4f9b\u4e24\u79cd\u80fd\u91cf/\u52a8\u91cf\u6b66\u5668\u7684\u53d1\u5c04\u529f\u80fd,\u751a\u81f3\u53ef\u4ee5\u901a\u8fc7\u8fd9\u4e2a\u62f3\u5957\u94fe\u63a5ae\u7f51\u7edc,\u4f46\u968f\u4e4b\u800c\u6765\u7684\u662f\u9ad8\u8d35\u7684\u9020\u4ef7.");
mods.thaumcraft.Research.addPrereq("MPSHAND", "MPS", false);
mods.thaumcraft.Warp.addToResearch("MPSHAND", 3);
mods.thaumcraft.Infusion.addRecipe("MPSHAND", <Thaumcraft:ItemPrimalCrusher>, [<IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <IC2:itemPartIridium>, <powersuits:powerArmorComponent:16>, <powersuits:powerArmorComponent:11>, <powersuits:powerArmorComponent:19>, <powersuits:powerArmorComponent:12>, <powersuits:powerArmorComponent:18>, <powersuits:powerArmorComponent:10>, <powersuits:powerArmorComponent:21>], "auram 128, lux 168, venenum 128, tutamen 128, fames 64, fabrico 256", <powersuits:item.powerFist>, 20);
mods.thaumcraft.Research.addInfusionPage("MPSHAND", <powersuits:item.powerFist>);
mods.thaumcraft.Research.refreshResearchRecipe("MPSHAND");
mods.thaumcraft.Research.moveResearch("MPSHAND", "ELDRITCH", 12, 6);